#! /bin/csh
# Make the time test collection.  Change first 4 pathnames as appropriate.
# Cacm collection obtainable in ~ftp/pub/smart/cacm on  ftp.cs.cornell.edu

set bin =     /home/smart/src/bin
set src = /home/smart/src
set tlibdir = /home/smart/lib

set current = $src/test_time
set database = $current/indexed
set database_stem = $database/with_stem
set database_no_stem = $database/with_no_stem

set coll     = $current/coll
set doc_loc = $coll/TIME.ALL
set query_loc = $coll/TIME.QUE

# CREATE NEW EMPTY COLLECTION
/bin/rm -rf $database
mkdir $database

### CREATE EMPTY COLLECTION <- WITH STEM
mkdir $database_stem
cat > $database_stem/spec << EOF1
## INFORMATION LOCATIONS
database                $database_stem
include_file            $tlibdir/spec.expcoll
doc_loc                 $database_stem/doc_loc
query_loc               $database_stem/query_loc
qrels_text_file         $coll/TIME.REL

## TIME DOCDESC
#### GENERIC PREPARSER
num_pp_sections                 1
pp_section.0.string             "*TEXT"
pp_section.0.newdoc_flag        true
pp_section.0.section_name       w

#### DESCRIPTION OF PARSE INPUT
index.num_sections              1
index.section.0.name            w
  index.section.0.method        index.parse_sect.full
  index.section.0.word.ctype    0
  index.section.0.word.stop_file  $coll/TIME.STP
  index.section.0.proper.ctype  0
title_section -1

#### DESCRIPTION OF FINAL VECTORS
num_ctypes                      1
ctype.0.name                    word

## ALTERATIONS OF STANDARD PARAMETERS
rmode                           SRDONLY|SMMAP
rwmode                          SRDWR|SINCORE
rwcmode                         SRDWR|SCREATE|SINCORE

EOF1

echo ""

# Copy auxiliary files to collection
echo Creating new database with STEM at `date`
echo "$doc_loc" > $database_stem/doc_loc
echo "$query_loc" > $database_stem/query_loc

# Index the collection
echo Indexing docs,queries,rels with STEM at `date`
$bin/smart exp_coll $database_stem/spec

# ====================================================
### CREATE EMPTY COLLECTION <- WITH NO STEM
mkdir $database_no_stem
cat > $database_no_stem/spec << EOF1
## INFORMATION LOCATIONS
database                $database_stem
include_file            $tlibdir/spec.expcoll
doc_loc                 $database_stem/doc_loc
query_loc               $database_stem/query_loc
qrels_text_file         $coll/TIME.REL

## TIME DOCDESC
#### GENERIC PREPARSER
num_pp_sections                 1
pp_section.0.string             "*TEXT"
pp_section.0.newdoc_flag        true
pp_section.0.section_name       w

#### DESCRIPTION OF PARSE INPUT
index.num_sections              1
index.section.0.name            w
  index.section.0.method        index.parse_sect.full
  index.section.0.word.ctype    0
  index.section.0.word.stop_file  $coll/TIME.STP
  index.section.0.proper.ctype  0
  index.section.0.word.stem_wanted 0
title_section -1

#### DESCRIPTION OF FINAL VECTORS
num_ctypes                      1
ctype.0.name                    word

## ALTERATIONS OF STANDARD PARAMETERS
rmode                           SRDONLY|SMMAP
rwmode                          SRDWR|SINCORE
rwcmode                         SRDWR|SCREATE|SINCORE

EOF1


echo ""

echo Creating new database without STEM at `date`
echo "$doc_loc" > $database_no_stem/doc_loc
echo "$query_loc" > $database_no_stem/query_loc


echo Indexing docs,queries,rels with STEM at `date`
$bin/smart exp_coll $database_no_stem/spec

echo ""
echo All done at `date`
echo ""