#! /bin/csh
# Make the med test collection.  Change first 4 pathnames as appropriate.
# Med collection obtainable in ~ftp/pub/smart/med on  ftp.cs.cornell.edu

set bin =     /home/smart/src/bin
set srcdir = /home/smart/src
set tlibdir = /home/smart/lib

set current = $srcdir/test_med
set database = $current/indexed
set database_stem = $database/with_stem
set database_no_stem = $database/with_no_stem

set coll     = $current/coll
set doc_loc = $coll/MED.ALL
set query_loc = $coll/MED.QRY

# CREATE NEW EMPTY COLLECTION
/bin/rm -rf $database
mkdir $database

### CREATE EMPTY COLLECTION <- WITH STEM
mkdir $database_stem
cat > $database_stem/spec << EOF1
## INFORMATION LOCATIONS
database                $database_stem
include_file            $tlibdir/spec.expcoll
doc_loc                 $database_stem/doc_loc
query_loc               $database_stem/query_loc
qrels_text_file         $coll/MED.REL

## MED DOCDESC
#### GENERIC PREPARSER
num_pp_sections                 3
pp_section.0.string             ".I"
pp_section.0.action             discard
pp_section.0.oneline_flag       true
pp_section.0.newdoc_flag        true
pp_section.1.string             ".W"
pp_section.1.section_name       w
pp_section.2.string             ".O"
pp_section.2.action             discard

#### DESCRIPTION OF PARSE INPUT
index.num_sections              1
index.section.0.name            w
  index.section.0.method        index.parse_sect.full
  index.section.0.word.ctype    0
  index.section.0.proper.ctype  0
title_section 0

#### DESCRIPTION OF FINAL VECTORS
num_ctypes                      1
ctype.0.name                    words

## ALTERATIONS OF STANDARD PARAMETERS
rmode                           SRDONLY|SMMAP
rwmode                          SRDWR|SINCORE
rwcmode                         SRDWR|SCREATE|SINCORE
dict_file_size                  20011

## ALTERATIONS OF STANDARD PROCEDURES
EOF1

echo ""

# Copy auxiliary files to collection
echo Creating new database at `date`
echo "$doc_loc" > $database_stem/doc_loc
echo "$query_loc" > $database_stem/query_loc

#index the collection
echo Indexing docs,queries,rels at `date`
$bin/smart exp_coll $database_stem/spec




# ====================================================
### CREATE EMPTY COLLECTION <- WITHOUT STEM
mkdir $database_no_stem
cat > $database_no_stem/spec << EOF1
## INFORMATION LOCATIONS
database                $database_no_stem
include_file            $tlibdir/spec.expcoll
doc_loc                 $database_no_stem/doc_loc
query_loc               $database_no_stem/query_loc
qrels_text_file         $coll/MED.REL.OLD

## MED DOCDESC
#### GENERIC PREPARSER
num_pp_sections                 3
pp_section.0.string             ".I"
pp_section.0.action             discard
pp_section.0.oneline_flag       true
pp_section.0.newdoc_flag        true
pp_section.1.string             ".W"
pp_section.1.section_name       w
pp_section.2.string             ".O"
pp_section.2.action             discard

#### DESCRIPTION OF PARSE INPUT
index.num_sections              1
index.section.0.name            w
  index.section.0.method        index.parse_sect.full
  index.section.0.word.ctype    0
  index.section.0.word.stem_wanted 0
  index.section.0.proper.ctype  0
title_section 0

#### DESCRIPTION OF FINAL VECTORS
num_ctypes                      1
ctype.0.name                    words

## ALTERATIONS OF STANDARD PARAMETERS
rmode                           SRDONLY|SMMAP
rwmode                          SRDWR|SINCORE
rwcmode                         SRDWR|SCREATE|SINCORE
dict_file_size                  20011

## ALTERATIONS OF STANDARD PROCEDURES
EOF1

echo ""

# Copy auxiliary files to collection
echo Creating new database at `date`
echo "$doc_loc" > $database_no_stem/doc_loc
echo "$query_loc" > $database_no_stem/query_loc

#index the collection
echo Indexing docs,queries,rels at `date`
$bin/smart exp_coll $database_no_stem/spec

echo ""
echo All done at `date`
echo ""echo "Create ntn versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ntn   query_weight ntn
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ntn   doc_weight ntn
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ntn  out inv.ntn

echo "Create nnc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.nnc   query_weight nnc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.nnc   doc_weight nnc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.nnc  out inv.nnc

echo "Create ntc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ntc   query_weight ntc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ntc   doc_weight ntc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ntc  out inv.ntc

echo "Create bnn versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.bnn   query_weight bnn
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.bnn   doc_weight bnn
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.bnn  out inv.bnn

echo "Create btn versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.btn   query_weight btn
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.btn   doc_weight btn
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.btn  out inv.btn

echo "Create bnc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.bnc   query_weight bnc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.bnc   doc_weight bnc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.bnc  out inv.bnc

echo "Create btc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.btc   query_weight btc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.btc   doc_weight btc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.btc  out inv.btc

echo "Create ann versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ann   query_weight ann
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ann   doc_weight ann
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ann  out inv.ann

echo "Create atn versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.atn   query_weight atn
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.atn   doc_weight atn
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.atn  out inv.atn

echo "Create anc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.anc   query_weight anc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.anc   doc_weight anc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.anc  out inv.anc

echo "Create atc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.atc   query_weight atc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.atc   doc_weight atc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.atc  out inv.atc

echo "Create lnn versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.lnn   query_weight lnn
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.lnn   doc_weight lnn
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.lnn  out inv.lnn

echo "Create ltn versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ltn   query_weight ltn
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ltn   doc_weight ltn
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ltn  out inv.ltn

echo "Create lnc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.lnc   query_weight lnc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.lnc   doc_weight lnc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.lnc  out inv.lnc

echo "Create ltc versions at `date`"
$bin/smart convert $database_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ltc   query_weight ltc
$bin/smart convert $database_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ltc   doc_weight ltc
$bin/smart convert $database_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ltc  out inv.ltc

echo "Create ntn versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ntn   query_weight ntn
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ntn   doc_weight ntn
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ntn  out inv.ntn

echo "Create nnc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.nnc   query_weight nnc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.nnc   doc_weight nnc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.nnc  out inv.nnc

echo "Create ntc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ntc   query_weight ntc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ntc   doc_weight ntc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ntc  out inv.ntc

echo "Create bnn versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.bnn   query_weight bnn
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.bnn   doc_weight bnn
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.bnn  out inv.bnn

echo "Create btn versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.btn   query_weight btn
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.btn   doc_weight btn
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.btn  out inv.btn

echo "Create bnc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.bnc   query_weight bnc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.bnc   doc_weight bnc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.bnc  out inv.bnc

echo "Create btc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.btc   query_weight btc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.btc   doc_weight btc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.btc  out inv.btc

echo "Create ann versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ann   query_weight ann
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ann   doc_weight ann
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ann  out inv.ann

echo "Create atn versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.atn   query_weight atn
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.atn   doc_weight atn
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.atn  out inv.atn

echo "Create anc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.anc   query_weight anc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.anc   doc_weight anc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.anc  out inv.anc

echo "Create atc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.atc   query_weight atc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.atc   doc_weight atc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.atc  out inv.atc

echo "Create lnn versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.lnn   query_weight lnn
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.lnn   doc_weight lnn
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.lnn  out inv.lnn

echo "Create ltn versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ltn   query_weight ltn
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ltn   doc_weight ltn
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ltn  out inv.ltn

echo "Create lnc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.lnc   query_weight lnc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.lnc   doc_weight lnc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.lnc  out inv.lnc

echo "Create ltc versions at `date`"
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_query \
                   in query.nnn  out query.ltc   query_weight ltc
$bin/smart convert $database_no_stem/spec   proc convert.obj.weight_doc \
                   in doc.nnn  out doc.ltc   doc_weight ltc
$bin/smart convert $database_no_stem/spec   proc convert.obj.vec_aux  \
                   in doc.ltc  out inv.ltc

